### ISSUE TITLE
와우

### ISSUE THREAD

**Issue by uuccu** [yutaejeong/algorithm-problem-solving#1]
알고있겠지만 백준, 프로그래머스, 리트코드는 플러그인이있어서 자동으로 커밋해주는데 안쓰는 이유가 있나요??
또 . 왜main 브랜치 하나로 통합 안하나요?

**Comment by uuccu** [comment]
왜 내말 무시해

**Comment by uuccu** [comment]
킹받는군 왜 무시하냐고!

**Comment by uuccu** [comment]
왜무시합니까!!!!

**Comment by uuccu** [comment]
냥냥!

**Comment by yutaejeong** [comment]
@uuccu 
1. 백준 플러그인이 있는 건 처음 알았는데, 크롬 확장 프로그램이더군요. 저는 사파리를 주로 씁니다.
2. 문제별로 브랜치를 나눴던 이유는 동시에 여러 문제를 풀던 중이었기 때문입니다. 물론, 이후에는 한동안 관성으로 지속했었습니다.

Github 알림이 회사 알림에 묻혔었는데, 퇴사하니 이제야 알림에 표시되네요.
